"""AsyncIO Flame core APIs. I/O methods use the caller's event loop."""

from flamepy.core.aio.cache import (
    delete_objects,
    download_object,
    get_object,
    patch_object,
    put_object,
    update_object,
    upload_object,
)
from flamepy.core.aio.client import Connection, Session, TaskIterator, TaskWatcher, connect
from flamepy.core.aio.service import FlameInstanceServer, FlameService, run
from flamepy.core.cache import ObjectKey, ObjectRef
from flamepy.core.types import (
    Application,
    ApplicationAttributes,
    ApplicationSchema,
    ApplicationState,
    Event,
    FlameClientTls,
    FlameContext,
    FlameError,
    FlameErrorCode,
    ResourceRequirement,
    SessionAttributes,
    SessionID,
    SessionState,
    Shim,
    Task,
    TaskID,
    TaskOptions,
    TaskState,
)

__all__ = [
    "Connection",
    "Session",
    "TaskIterator",
    "TaskWatcher",
    "connect",
    "ObjectKey",
    "ObjectRef",
    "Application",
    "ApplicationAttributes",
    "ApplicationSchema",
    "ApplicationState",
    "Event",
    "FlameClientTls",
    "FlameContext",
    "FlameError",
    "FlameErrorCode",
    "ResourceRequirement",
    "SessionAttributes",
    "SessionID",
    "SessionState",
    "Shim",
    "Task",
    "TaskID",
    "TaskOptions",
    "TaskState",
    "FlameInstanceServer",
    "FlameService",
    "run",
    "put_object",
    "get_object",
    "update_object",
    "patch_object",
    "delete_objects",
    "upload_object",
    "download_object",
]
