services:
  flame-session-manager:
    image: xflops/flame-session-manager:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.fsm
    environment:
      - RUST_LOG=info
    volumes:
      - ./ci/flame-cluster.yaml:/root/.flame/flame-cluster.yaml
      - ./ci/certs:/etc/flame/certs:ro
      - ./logs:/usr/local/flame/logs
    ports:
      - 8080:8080
    networks:
      - flame-net

  flame-object-cache:
    image: xflops/flame-object-cache:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.foc
    environment:
      - RUST_LOG=info
    volumes:
      - ./ci/flame-cluster.yaml:/root/.flame/flame-cluster.yaml
      - ./ci/certs:/etc/flame/certs:ro
      - flame-cache-storage:/var/lib/flame/cache
      - ./logs:/usr/local/flame/logs
    ports:
      - 9090:9090
    networks:
      - flame-net
    deploy:
      resources:
        limits:
          memory: 12G

  flame-executor-manager:
    image: xflops/flame-executor-manager:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.fem
    environment:
      - RUST_LOG=info
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - flame-object-cache
    volumes:
      - ./ci/flame-cluster.yaml:/root/.flame/flame-cluster.yaml
      - ./ci/certs:/etc/flame/certs:ro
      - ./examples:/opt/examples
      - ./e2e:/opt/e2e
      - flame-work:/usr/local/flame/work
      - ./logs:/usr/local/flame/logs
      - ./work/cache:/usr/local/flame/data/cache
    networks:
      - flame-net

  flame-console:
    image: xflops/flame-console:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.console
    environment:
      - RUST_LOG=info
    volumes:
      - ./ci/flame.yaml:/root/.flame/flame.yaml
      - ./ci/certs:/etc/flame/certs:ro
      - ./examples:/opt/examples
      - ./e2e:/opt/e2e
      - ./work/cache:/usr/local/flame/data/cache
    depends_on:
      - flame-object-cache
    networks:
      - flame-net

networks:
  flame-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  flame-work:
  flame-cache-storage:
