# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import flamepy.types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x05\x66lame\x1a\x0btypes.proto\"C\n\x06Object\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"A\n\x0eObjectMetadata\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x0c\n\x04size\x18\x03 \x01(\x04\".\n\x10PutObjectRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\" \n\x10GetObjectRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"#\n\x13\x44\x65leteObjectRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t2\xe0\x01\n\x0bObjectCache\x12\x37\n\x03Put\x12\x17.flame.PutObjectRequest\x1a\x15.flame.ObjectMetadata\"\x00\x12/\n\x03Get\x12\x17.flame.GetObjectRequest\x1a\r.flame.Object\"\x00\x12\x30\n\x06Update\x12\r.flame.Object\x1a\x15.flame.ObjectMetadata\"\x00\x12\x35\n\x06\x44\x65lete\x12\x1a.flame.DeleteObjectRequest\x1a\r.flame.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBJECT']._serialized_start=35
  _globals['_OBJECT']._serialized_end=102
  _globals['_OBJECTMETADATA']._serialized_start=104
  _globals['_OBJECTMETADATA']._serialized_end=169
  _globals['_PUTOBJECTREQUEST']._serialized_start=171
  _globals['_PUTOBJECTREQUEST']._serialized_end=217
  _globals['_GETOBJECTREQUEST']._serialized_start=219
  _globals['_GETOBJECTREQUEST']._serialized_end=251
  _globals['_DELETEOBJECTREQUEST']._serialized_start=253
  _globals['_DELETEOBJECTREQUEST']._serialized_end=288
  _globals['_OBJECTCACHE']._serialized_start=291
  _globals['_OBJECTCACHE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
