---
current-context: flame
contexts:
  - name: flame
    cluster:
      endpoint: "https://flame-session-manager:8080"
      tls:
        ca_file: "/etc/flame/certs/ca.crt"
        cert_file: "/etc/flame/certs/admin.crt"
        key_file: "/etc/flame/certs/admin.key"
    cache:
      endpoint: "grpcs://flame-object-cache:9090"
      tls:
        ca_file: "/etc/flame/certs/ca.crt"
        cert_file: "/etc/flame/certs/admin.crt"
        key_file: "/etc/flame/certs/admin.key"
