# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flamepy.proto.cache_pb2 as cache__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectCacheServiceStub(object):
    """The cache stores opaque bytes. Clients serialize and deserialize values,
    including Arrow values, before sending them over this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.stream_unary(
                '/flame.v1.ObjectCacheService/Put',
                request_serializer=cache__pb2.CacheWriteRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheObjectMetadata.FromString,
                _registered_method=True)
        self.Patch = channel.stream_unary(
                '/flame.v1.ObjectCacheService/Patch',
                request_serializer=cache__pb2.CacheWriteRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheObjectMetadata.FromString,
                _registered_method=True)
        self.Get = channel.unary_stream(
                '/flame.v1.ObjectCacheService/Get',
                request_serializer=cache__pb2.CacheGetRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheGetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/flame.v1.ObjectCacheService/Delete',
                request_serializer=cache__pb2.CacheDeleteRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheDeleteResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/flame.v1.ObjectCacheService/GetMetadata',
                request_serializer=cache__pb2.CacheGetMetadataRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheObjectMetadata.FromString,
                _registered_method=True)
        self.List = channel.unary_stream(
                '/flame.v1.ObjectCacheService/List',
                request_serializer=cache__pb2.CacheListRequest.SerializeToString,
                response_deserializer=cache__pb2.CacheObjectMetadata.FromString,
                _registered_method=True)


class ObjectCacheServiceServicer(object):
    """The cache stores opaque bytes. Clients serialize and deserialize values,
    including Arrow values, before sending them over this service.
    """

    def Put(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Patch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectCacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.stream_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=cache__pb2.CacheWriteRequest.FromString,
                    response_serializer=cache__pb2.CacheObjectMetadata.SerializeToString,
            ),
            'Patch': grpc.stream_unary_rpc_method_handler(
                    servicer.Patch,
                    request_deserializer=cache__pb2.CacheWriteRequest.FromString,
                    response_serializer=cache__pb2.CacheObjectMetadata.SerializeToString,
            ),
            'Get': grpc.unary_stream_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=cache__pb2.CacheGetRequest.FromString,
                    response_serializer=cache__pb2.CacheGetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=cache__pb2.CacheDeleteRequest.FromString,
                    response_serializer=cache__pb2.CacheDeleteResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=cache__pb2.CacheGetMetadataRequest.FromString,
                    response_serializer=cache__pb2.CacheObjectMetadata.SerializeToString,
            ),
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=cache__pb2.CacheListRequest.FromString,
                    response_serializer=cache__pb2.CacheObjectMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flame.v1.ObjectCacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flame.v1.ObjectCacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectCacheService(object):
    """The cache stores opaque bytes. Clients serialize and deserialize values,
    including Arrow values, before sending them over this service.
    """

    @staticmethod
    def Put(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/flame.v1.ObjectCacheService/Put',
            cache__pb2.CacheWriteRequest.SerializeToString,
            cache__pb2.CacheObjectMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Patch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/flame.v1.ObjectCacheService/Patch',
            cache__pb2.CacheWriteRequest.SerializeToString,
            cache__pb2.CacheObjectMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flame.v1.ObjectCacheService/Get',
            cache__pb2.CacheGetRequest.SerializeToString,
            cache__pb2.CacheGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flame.v1.ObjectCacheService/Delete',
            cache__pb2.CacheDeleteRequest.SerializeToString,
            cache__pb2.CacheDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flame.v1.ObjectCacheService/GetMetadata',
            cache__pb2.CacheGetMetadataRequest.SerializeToString,
            cache__pb2.CacheObjectMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/flame.v1.ObjectCacheService/List',
            cache__pb2.CacheListRequest.SerializeToString,
            cache__pb2.CacheObjectMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
