# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shim.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import flamepy.proto.types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nshim.proto\x12\x08\x66lame.v1\x1a\x0btypes.proto\"\xf6\x01\n\x12\x41pplicationContext\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x04shim\x18\x02 \x01(\x0e\x32\x0e.flame.v1.Shim\x12\x12\n\x05image\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x63ommand\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x1e\n\x11working_directory\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x10\n\x03url\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\x16\n\tinstaller\x18\x07 \x01(\tH\x04\x88\x01\x01\x42\x08\n\x06_imageB\n\n\x08_commandB\x14\n\x12_working_directoryB\x06\n\x04_urlB\x0c\n\n_installer\"\x81\x01\n\x0eSessionContext\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x31\n\x0b\x61pplication\x18\x02 \x01(\x0b\x32\x1c.flame.v1.ApplicationContext\x12\x18\n\x0b\x63ommon_data\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x42\x0e\n\x0c_common_data\"P\n\x0bTaskContext\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\x05input\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_input2\xc7\x01\n\x08Instance\x12>\n\x0eOnSessionEnter\x12\x18.flame.v1.SessionContext\x1a\x10.flame.v1.Result\"\x00\x12=\n\x0cOnTaskInvoke\x12\x15.flame.v1.TaskContext\x1a\x14.flame.v1.TaskResult\"\x00\x12<\n\x0eOnSessionLeave\x12\x16.flame.v1.EmptyRequest\x1a\x10.flame.v1.Result\"\x00\x42)Z\'github.com/flame-sh/flame/sdk/go/rpc/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/flame-sh/flame/sdk/go/rpc/v1'
  _globals['_APPLICATIONCONTEXT']._serialized_start=38
  _globals['_APPLICATIONCONTEXT']._serialized_end=284
  _globals['_SESSIONCONTEXT']._serialized_start=287
  _globals['_SESSIONCONTEXT']._serialized_end=416
  _globals['_TASKCONTEXT']._serialized_start=418
  _globals['_TASKCONTEXT']._serialized_end=498
  _globals['_INSTANCE']._serialized_start=501
  _globals['_INSTANCE']._serialized_end=700
# @@protoc_insertion_point(module_scope)
