"""
Copyright 2026 The Flame Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from typing import Any, Dict, Optional, Union

import cloudpickle

from flamepy.core import ObjectRef, get_object, put_object
from flamepy.core.client import (
    Session as CoreSession,
)
from flamepy.core.client import (
    create_session,
    open_session,
)
from flamepy.core.types import ResourceRequirement, short_name


class Session:
    """A streamlined interface for building and interacting with service sessions.

    The Session class is a thin wrapper around core.Session, where the service name
    corresponds to the application's name.

    Example:
        Direct instantiation:
            >>> session = Session("test", ctx)
            >>> resp = session.invoke(req)
            >>> session.close()

        Context manager:
            >>> with Session("test", ctx) as session:
            ...     resp = session.invoke(req)
    """

    def __init__(
        self,
        name: Optional[str] = None,
        ctx: Optional[Any] = None,
        session_id: Optional[str] = None,
        resreq: Optional[Union[ResourceRequirement, Dict[str, Any]]] = None,
    ):
        """Initialize a service session.

        Args:
            name: Optional application name.
                  Required if session_id is None. Mutually exclusive with session_id.
            ctx: Optional common data (context) for the session. Only used when creating a new session.
            session_id: Optional session ID. If provided, opens an existing session.
                        Required if name is None. Mutually exclusive with name.
            resreq: Optional explicit resource requirements. When omitted, the
                    server applies cluster.resource_requirement (or a hardcoded
                    fallback when that is unset). Can be a ResourceRequirement
                    or dict like {"cpu": 16, "memory": "64g", "gpu": 4}.

        Raises:
            ValueError: If both name and session_id are None, or if both are provided.
        """
        if name is None and session_id is None:
            raise ValueError("Either 'name' or 'session_id' must be provided")
        if name is not None and session_id is not None:
            raise ValueError("Cannot provide both 'name' and 'session_id'. They are mutually exclusive.")

        if isinstance(resreq, dict):
            memory = resreq.get("memory") or resreq.get("mem", 0)
            resreq = ResourceRequirement(
                cpu=resreq.get("cpu", 0),
                memory=ResourceRequirement._parse_memory(memory) if isinstance(memory, str) else memory,
                gpu=resreq.get("gpu", 0),
            )

        self._name = name
        self._session: Optional[CoreSession] = None

        if session_id is not None:
            # Open an existing session
            self._session = open_session(session_id)
            # Update name from the opened session if not provided
            if self._name is None:
                self._name = self._session.application
        else:
            # Create a new session using flamepy.create_session
            # For service module: serialize ctx with cloudpickle, put in cache to get ObjectRef,
            # then encode ObjectRef to bytes for core API
            common_data_bytes = None
            temp_session_id = None
            if ctx is not None:
                # Generate a temporary session_id for caching (will be regenerated by create_session if needed)
                temp_session_id = short_name(name)
                # Serialize the context using cloudpickle
                serialized_ctx = cloudpickle.dumps(ctx, protocol=cloudpickle.DEFAULT_PROTOCOL)
                # Put in cache with <app>/<session_id> key prefix
                key_prefix = f"{name}/{temp_session_id}"
                object_ref = put_object(key_prefix, serialized_ctx)
                # Encode ObjectRef to bytes for core API
                common_data_bytes = object_ref.encode()

            self._session = create_session(
                application=name,
                common_data=common_data_bytes,
                session_id=temp_session_id,
                resreq=resreq,
            )

    def invoke(self, req: Any) -> Any:
        """Invoke the service session with a request.

        The request and response objects should exactly match the service entrypoint
        signature defined on the service side.

        Args:
            req: The request object matching the service entrypoint signature

        Returns:
            The response object matching the service entrypoint signature

        Example:
            >>> resp = session.invoke(req)
        """
        if self._session is None:
            raise RuntimeError("Service session is not initialized")

        # For service module: serialize input with cloudpickle, call core API, then deserialize output
        input_bytes = cloudpickle.dumps(req, protocol=cloudpickle.DEFAULT_PROTOCOL)
        output_bytes = self._session.invoke(input_bytes)

        if output_bytes is None:
            return None

        # Deserialize output using cloudpickle
        return cloudpickle.loads(output_bytes)

    def context(self) -> Any:
        """Get the current service session context.

        Returns the session's shared (common) data, which represents the current
        session context such as a running conversation or environment state.

        Returns:
            The common data (context) of the session, or None if not set

        Example:
            >>> ctx = session.context()
        """
        if self._session is None:
            return None

        # For service module: get bytes from core API, decode to ObjectRef, get from cache, then deserialize
        common_data_bytes = self._session.common_data()
        if common_data_bytes is None:
            return None

        # Decode bytes to ObjectRef
        object_ref = ObjectRef.decode(common_data_bytes)
        # Get from cache
        serialized_ctx = get_object(object_ref)
        # Deserialize using cloudpickle
        return cloudpickle.loads(serialized_ctx)

    def id(self) -> Optional[str]:
        """Get the service session ID.

        Returns:
            The session ID, or None if the session is not initialized

        Example:
            >>> session_id = session.id()
        """
        if self._session is None:
            return None
        return self._session.id

    def close(self) -> None:
        """Close the service session and release resources.

        This closes the underlying session. After calling close(), the session
        should not be used anymore.
        """
        if self._session is not None:
            self._session.close()
            self._session = None

    def __enter__(self) -> "Session":
        """Enter the context manager."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        """Exit the context manager and close the session."""
        self.close()
        return False
