"""
Copyright 2026 The Flame Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from typing import Any, Optional

import cloudpickle

from flamepy.core import ObjectRef, get_object, put_object
from flamepy.core.client import (
    Session,
    create_session,
    open_session,
)
from flamepy.core.types import short_name


class Agent:
    """A streamlined interface for building and interacting with agents.

    The Agent class is a thin wrapper around core.Session, where the Agent's name
    corresponds to the application's name.

    Example:
        Direct instantiation:
            >>> agent = Agent("test", ctx)
            >>> resp = agent.invoke(req)
            >>> agent.close()

        Context manager:
            >>> with Agent("test", ctx) as agent:
            ...     resp = agent.invoke(req)
    """

    def __init__(
        self,
        name: Optional[str] = None,
        ctx: Optional[Any] = None,
        session_id: Optional[str] = None,
        slots: int = 1,
    ):
        """Initialize an Agent.

        Args:
            name: Optional application name (corresponds to the agent's name).
                  Required if session_id is None. Mutually exclusive with session_id.
            ctx: Optional common data (context) for the session. Only used when creating a new session.
            session_id: Optional session ID. If provided, opens an existing session.
                        Required if name is None. Mutually exclusive with name.
            slots: Number of slots for the session (default: 1). Only used when creating a new session.

        Raises:
            ValueError: If both name and session_id are None, or if both are provided.
        """
        if name is None and session_id is None:
            raise ValueError("Either 'name' or 'session_id' must be provided")
        if name is not None and session_id is not None:
            raise ValueError("Cannot provide both 'name' and 'session_id'. They are mutually exclusive.")

        self._name = name
        self._session: Optional[Session] = None

        if session_id is not None:
            # Open an existing session
            self._session = open_session(session_id)
            # Update name from the opened session if not provided
            if self._name is None:
                self._name = self._session.application
        else:
            # Create a new session using flamepy.create_session
            # For agent module: serialize ctx with cloudpickle, put in cache to get ObjectRef,
            # then encode ObjectRef to bytes for core API
            common_data_bytes = None
            temp_session_id = None
            if ctx is not None:
                # Generate a temporary session_id for caching (will be regenerated by create_session if needed)
                temp_session_id = short_name(name)
                # Serialize the context using cloudpickle
                serialized_ctx = cloudpickle.dumps(ctx, protocol=cloudpickle.DEFAULT_PROTOCOL)
                # Put in cache to get ObjectRef (use name as application_id)
                object_ref = put_object(name, temp_session_id, serialized_ctx)
                # Encode ObjectRef to bytes for core API
                common_data_bytes = object_ref.encode()

            # Create session - session_id is optional, create_session will generate one if not provided
            self._session = create_session(
                application=name,
                common_data=common_data_bytes,
                session_id=temp_session_id,  # Pass None if ctx is None, otherwise use temp_session_id
                slots=slots,
            )

    def invoke(self, req: Any) -> Any:
        """Invoke the agent with a request.

        The request and response objects should exactly match the agent's entrypoint
        signature defined on the service side.

        Args:
            req: The request object matching the agent's entrypoint signature

        Returns:
            The response object matching the agent's entrypoint signature

        Example:
            >>> resp = agent.invoke(req)
        """
        if self._session is None:
            raise RuntimeError("Agent session is not initialized")

        # For agent module: serialize input with cloudpickle, call core API, then deserialize output
        input_bytes = cloudpickle.dumps(req, protocol=cloudpickle.DEFAULT_PROTOCOL)
        output_bytes = self._session.invoke(input_bytes)

        if output_bytes is None:
            return None

        # Deserialize output using cloudpickle
        return cloudpickle.loads(output_bytes)

    def context(self) -> Any:
        """Get the current agent context.

        Returns the session's shared (common) data, which represents the current
        agent context such as a running conversation or environment state.

        Returns:
            The common data (context) of the session, or None if not set

        Example:
            >>> ctx = agent.context()
        """
        if self._session is None:
            return None

        # For agent module: get bytes from core API, decode to ObjectRef, get from cache, then deserialize
        common_data_bytes = self._session.common_data()
        if common_data_bytes is None:
            return None

        # Decode bytes to ObjectRef
        object_ref = ObjectRef.decode(common_data_bytes)
        # Get from cache
        serialized_ctx = get_object(object_ref)
        # Deserialize using cloudpickle
        return cloudpickle.loads(serialized_ctx)

    def id(self) -> Optional[str]:
        """Get the agent's session ID.

        Returns:
            The session ID of the agent, or None if the session is not initialized

        Example:
            >>> agent_id = agent.id()
        """
        if self._session is None:
            return None
        return self._session.id

    def close(self) -> None:
        """Close the agent and release resources.

        This closes the underlying session. After calling close(), the agent
        should not be used anymore.
        """
        if self._session is not None:
            self._session.close()
            self._session = None

    def __enter__(self) -> "Agent":
        """Enter the context manager."""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        """Exit the context manager and close the agent."""
        self.close()
        return False
