ALTER TABLE sessions ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE tasks ADD COLUMN version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE applications ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
