{{- include "flame.validate" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flame.configMapName" . }}
  labels:
    {{- include "flame.labels" . | nindent 4 }}
data:
  flame-cluster.yaml: |
    ---
    cluster:
      name: {{ .Values.cluster.name | quote }}
      endpoint: {{ include "flame.clusterEndpoint" . | quote }}
      resreq: {{ .Values.cluster.resreq | quote }}
      policies:
        {{- range .Values.cluster.policies }}
        - {{ . | quote }}
        {{- end }}
      storage: {{ .Values.cluster.storage | quote }}
      schedule_interval: {{ .Values.cluster.scheduleInterval }}
      executors:
        shim: {{ .Values.cluster.executors.shim | quote }}
      limits:
        max_sessions: {{ .Values.cluster.limits.maxSessions }}
        max_executors: {{ .Values.cluster.limits.maxExecutors }}
      recovery:
        session:
          retry_limits: {{ .Values.cluster.recovery.session.retryLimits }}
    {{- if .Values.security.enabled }}
    security:
      trust_domain: {{ .Values.security.trustDomain | quote }}
      tls:
        cert_file: {{ printf "%s/tls.crt" (include "flame.tlsPath" .) | quote }}
        key_file: {{ printf "%s/tls.key" (include "flame.tlsPath" .) | quote }}
        ca_file: {{ printf "%s/ca.crt" (include "flame.tlsPath" .) | quote }}
    {{- end }}
    cache:
      endpoint: {{ include "flame.cacheEndpoint" . | quote }}
      network_interface: {{ .Values.objectCache.networkInterface | quote }}
      storage: {{ .Values.objectCache.storage | quote }}
      eviction:
        policy: {{ .Values.objectCache.eviction.policy | quote }}
        max_memory: {{ .Values.objectCache.eviction.maxMemory | quote }}
        {{- if .Values.objectCache.eviction.maxObjects }}
        max_objects: {{ .Values.objectCache.eviction.maxObjects }}
        {{- end }}
      gc:
        interval: {{ .Values.objectCache.gc.interval | quote }}
  {{- if .Values.clientConfig.enabled }}
  flame.yaml: |
    ---
    current-context: {{ .Values.cluster.name | quote }}
    contexts:
      - name: {{ .Values.cluster.name | quote }}
        cluster:
          endpoint: {{ include "flame.clusterEndpoint" . | quote }}
          {{- if .Values.security.enabled }}
          tls:
            cert_file: {{ .Values.clientConfig.tls.certFile | quote }}
            key_file: {{ .Values.clientConfig.tls.keyFile | quote }}
            ca_file: {{ .Values.clientConfig.tls.caFile | quote }}
          {{- end }}
        cache:
          endpoint: {{ include "flame.cacheEndpoint" . | quote }}
        {{- if .Values.security.enabled }}
          tls:
            cert_file: {{ .Values.clientConfig.tls.certFile | quote }}
            key_file: {{ .Values.clientConfig.tls.keyFile | quote }}
            ca_file: {{ .Values.clientConfig.tls.caFile | quote }}
        {{- end }}
  {{- end }}
