metadata:
  name: flmrun
spec:
  shim: host
  description: The Flame App application for executing customized Python applications.
  command: ${FLAME_HOME}/bin/uv
  arguments:
    - run
    - --python
    - python${FLAME_PYTHON_VERSION}
    - python
    - -m
    - flamepy.app.runpy
  installer: python
  schema: {}
