name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: Rust E2E Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest
      - name: Generate TLS certificates
        run: |
          chmod +x ci/generate-certs.sh
          ci/generate-certs.sh -o ci/certs -s "flame-session-manager,flame-executor-manager,flame-object-cache,localhost,127.0.0.1" -i "172.20.0.0/24"
      - name: Start Flame
        run: |
          cp ci/flame-cluster-docker.yaml ci/flame-cluster.yaml
          docker compose up --build --force-recreate -d
      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Run Rust E2E Test
        run: |
          make e2e-rs

