name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Generate TLS certificates
        run: |
          chmod +x ci/generate-certs.sh
          ci/generate-certs.sh -o ci/certs -s "flame-session-manager,flame-executor-manager,flame-object-cache,localhost,127.0.0.1" -i "172.20.0.0/24"

      - name: Start Flame with benchmark config
        run: |
          cp ci/flame-cluster-benchmark.yaml ci/flame-cluster.yaml
          docker compose up --build --force-recreate -d

      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Run Rust E2E Tests
        env:
          FLAME_ROOT: ${{ github.workspace }}
        run: |
          make e2e-rs

      - name: Show logs on failure
        if: failure()
        run: |
          docker compose logs flame-session-manager
          docker compose logs flame-executor-manager
